### ISSUE TITLE
Request: Flag to make whole sheet draggable/only header

### ISSUE THREAD

**Issue by marcinbittel** [Temzasse/react-modal-sheet#10]
Hey,

As I can see in commits history that the SheetContent was not a draggable component in the past, is there a chance to provide functionality to disable drag on SheetContent eg. by adding some component props?

**Comment by Temzasse** [comment]
This should be quite easy to add but I have to think about what the API will be for these kinds of modifiers.

This somewhat relates to the other issue about disabling the closing of the sheet. Maybe both of these could be solved by a unified solution 🤔

**Comment by Temzasse** [comment]
I added `disabledDrag` prop that can be used to disable dragging for the whole sheet or its subparts.

Please take a look at the [Sheet.Content props](https://github.com/Temzasse/react-modal-sheet#content-props) section in the docs.

I hope this solves your issue 🙂

**Comment by Temzasse** [comment]
Oh yeah and remember to update the lib to v1.3.0.

**Comment by marcinbittel** [comment]
Thank you for the quick reply! :)
