### ISSUE TITLE
How I can disable animation when the bottom sheet closing?

### ISSUE THREAD

**Issue by erhnml** [Temzasse/react-modal-sheet#104]
When the model after closed I can't click anything during 1-2s. I think there is some animation. How can I disable that animation?

**Comment by shouze** [comment]
ping @erhnml we face the same issue, so as you've closed this one, could you please share how did you solve it?

**Comment by erhnml** [comment]
Hi, @shouze I don't remember :( Now I am using another bottom sheet https://www.npmjs.com/package/react-spring-bottom-sheet.
