### ISSUE TITLE
Suggestion:  add compatibility with Tailwind

### ISSUE THREAD

**Issue by felpsio** [Temzasse/react-modal-sheet#109]
I would like to be able to style the components using tailwind classes instead of using `style` directly.

**Comment by Temzasse** [comment]
Thank you for the suggestion but this is not something we aim to support in this library 🙂 

You can take a look at [NativeWind](https://www.nativewind.dev/) if you want to use Tailwind with React Native.

**Comment by Temzasse** [comment]
Thank you for raising this issue 👍🏻 I will add support for giving a `className` for the various sheet components which will enabled Tailwind support 🙂

**Comment by felpsio** [comment]
Thanks. Also thanks a lot for this amazing library! :D

**Comment by Temzasse** [comment]
Adding a `className` to the various sheet components was released in [v1.9.0](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.9.0).

This should enabled Tailwind support 😊
