### ISSUE TITLE
Not able to do horizontal scroll on IOS

### ISSUE THREAD

**Issue by lucasluca** [Temzasse/react-modal-sheet#110]
I'm trying to scroll horizontally, on android works OK, but not on IOS, anyone had the same issue?

**Comment by Temzasse** [comment]
Thanks for reporting this 👍🏻 

I've narrowed the problem down to `usePreventScroll` hook that this library uses internally.
I still need to figure out how to fix this scrolling issue while preserving body scroll locking functionality 🤔

**Comment by Temzasse** [comment]
Related issue: https://github.com/adobe/react-spectrum/issues/3779

**Comment by Temzasse** [comment]
This should be fixed in [v1.10.0](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.10.0).

I ended up copying the `usePreventScrolll` implementation to the repo and applied [this fix](https://github.com/adobe/react-spectrum/pull/3780) to it.
