### ISSUE TITLE
Infinite scroll doesn't Effect

### ISSUE THREAD

**Issue by yahyafakhroji** [Temzasse/react-modal-sheet#111]
Hi there,

I implemented Infinite scroll on this component, but the data on the next page can't be recalled, and even no trigger is called. whereas when I use the box page, it works. Thanks 🙏

**Comment by Temzasse** [comment]
Hey 👋

Please provide a reproduction example with a more detailed explanation of the problem 🙂

**Comment by Temzasse** [comment]
Closing this due to no reproduction provided.
