### ISSUE TITLE
Close on clicking outside

### ISSUE THREAD

**Issue by fishuke** [Temzasse/react-modal-sheet#114]
I don't know if it's an already implemented function but I need it. I can implement it manually but would appreciate it if it would be a feature.

**Comment by fishuke** [comment]
@Temzasse

**Comment by Temzasse** [comment]
Yep it is implemented: https://github.com/Temzasse/react-modal-sheet/blob/master/example/components/SnapPoints.tsx#L50

**Comment by JcbPrn** [comment]
Where is this an answer to the question? I don't get it.
