### ISSUE TITLE
zIndex should be set to -1 when Sheet is closed

### ISSUE THREAD

**Issue by younes0** [Temzasse/react-modal-sheet#117]
Otherwise it causes unexpected changes (disabling [Embla carousel ](https://www.embla-carousel.com/)scrolling for instance)

This is my workaround:
```
<Sheet
   {...}
    style={{
      zIndex: isOpen ? 1000 : -1,
    }}
 >
 {...}
 </Sheet>
```

**Comment by Temzasse** [comment]
Good suggestion 👍🏻

**Comment by Temzasse** [comment]
Fixed in https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.11.0
