### ISSUE TITLE
Feature Request: horizontal instead of vertical?

### ISSUE THREAD

**Issue by airtonix** [Temzasse/react-modal-sheet#119]
Looks like react-modal-sheet only supports stacks that open from the bottom? 

can we get opening from top,left and right as well ?

**Comment by Temzasse** [comment]
Hi 👋🏻 Can you give me an example of this? For example screen recording of an existing app that has this kind of animation 🙂 

The idea react-modal-sheet is to implement a bottom sheet which like the name suggests opens from the bottom.

**Comment by saman2007** [comment]
hello. i came to suggest this feature and i saw that @airtonix did this already. he's right. it is really good to support every sides (left, right, bottom, top and even center). for example i am currently working on a project that has a modal that opens from right and an other modal that opens from left. user can close and open these modals by swipping a button to left and right. if i could use this package for this purpose it would be great! actually my project has a bottom modal too and i use this package for this modal.

thank you and good luck :)

**Comment by Temzasse** [comment]
Unfortunately I don't currently have the time to work on adding a horizontal version of this library. I'll close this issue but I would be happy to review a PR if someone wants to implement this feature 🙂
