### ISSUE TITLE
Drag on body should not take effect when I'm trying to scroll the content up from standstill

### ISSUE THREAD

**Issue by xsjcTony** [Temzasse/react-modal-sheet#128]
See in the video that the modal is dragged down when I'm trying to scroll the content up from standstill.

Using official example. @Temzasse Please have a look. Appreciate that ❤️

https://github.com/Temzasse/react-modal-sheet/assets/45784210/d73dcc66-8c3d-4374-9a20-93a67fe05258

**Comment by Temzasse** [comment]
Duplicate of https://github.com/Temzasse/react-modal-sheet/issues/122.

Unfortunately scrolling in conjunction with dragging is kindah an unsolved problem on the web 😿 
If you have any suggestion for solving this problem that would be welcome 🙏🏻
