### ISSUE TITLE
Glitchy behaviour when swiping on scrollable content

### ISSUE THREAD

**Issue by 10000multiplier** [Temzasse/react-modal-sheet#13]
https://user-images.githubusercontent.com/57633368/113315177-04be3700-92db-11eb-8661-117042e0e7d0.mp4

**Comment by Temzasse** [comment]
Can you elaborate on what is happening here and what is the expected behaviour?

Dragging very small amounts can look a bit janky but I'm not sure if there is anything to be done for that since Framer Motion is responsible of doing the animation work.

**Comment by Temzasse** [comment]
Please try updating to `v1.3.2` and see if it resolves your issue 🙏🏻 

Everything should work a bit more smoothly now that only one motion value is animated for both dragging and snapping to top, bottom, or snap points 🙂

**Comment by 10000multiplier** [comment]
Awesome. 

I'm in love with your library!
