### ISSUE TITLE
`onClick` is missing from backdrop props

### ISSUE THREAD

**Issue by 12joan** [Temzasse/react-modal-sheet#131]
#### Issue summary
Adding an `onClick` handler to the Backdrop component seems to be a supported use case, but `onClick` is missing from the component's prop type.

#### Code sandbox
https://codesandbox.io/s/practical-swartz-6h6shx?file=/src/App.tsx:132-171

```
Type '{ onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & SheetBackdropProps & RefAttributes<any>'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & SheetBackdropProps & RefAttributes<any>'.ts(2322)
```

#### Expected behaviour
If components like Backdrop are passing rest props to the underlying HTML element, then the prop types for that HTML element should be included in the component prop type.

**Comment by Temzasse** [comment]
Most sheet components are `motion` components from Framer Motion so instead of `onClick` they have `onTap`.

**Comment by 12joan** [comment]
@Temzasse Thanks for pointing that out! 😅

Maybe this could be documented [here](https://github.com/Temzasse/react-modal-sheet#sheetbackdrop) for people like me who aren't familiar with Framer Motion?
