### ISSUE TITLE
Unable to scroll behind the sheet, but able to click

### ISSUE THREAD

**Issue by AlexandrosGounis** [Temzasse/react-modal-sheet#139]
Even without a `Backdrop` the content behind the sheet is not scrollable, but it is clickable.
It is likely that the suggestion in pull request #138 can add functionality to resolve this.
This is due to the `scroll-locking` behaviour by default.

**Comment by Temzasse** [comment]
PR #138 has been merged and `disableScrollLocking` is now released in [v2.1.0](https://github.com/Temzasse/react-modal-sheet/releases/tag/v2.1.0).
