### ISSUE TITLE
Feature request: add option to unblock backdrop while modal is opened

### ISSUE THREAD

**Issue by 10000multiplier** [Temzasse/react-modal-sheet#14]
It would be nice if a dropdown menu in a navbar could still work while the modal was open.

Awesome project!

**Comment by 10000multiplier** [comment]
actually I found a way around this.

just add `style={{ isolation: 'isolate', zIndex: 9999999 }}` to the component you want to elevate.

**Comment by Temzasse** [comment]
Glad you figured it out! 🙂 👍🏻
