### ISSUE TITLE
How do I implement a sticky footer?

### ISSUE THREAD

**Issue by 0oooooooo0** [Temzasse/react-modal-sheet#147]
How do I implement a sticky footer?
I also want to use it with Sheet.Scroller

**Comment by Temzasse** [comment]
Hi @0oooooooo0 👋

You could try to use snap points to place the sheet at the bottom and make it look like a "sticky" footer.

However I would recommend not to use the bottom sheet as a sticky footer but instead create a separate component as the sticky footer that then opens the sheet like I've done in the Apple Music [demo](https://github.com/Temzasse/react-modal-sheet/blob/main/example/components/apple-music/index.tsx).

**Comment by WZG99** [comment]
Hi, is it possible to have a sticky footer inside the Modal Sheet ? Something like <Sheet.Footer>. 

By modifying from the example provided in documentation: 

return (
    <>
      <button onClick={() => setOpen(true)}>Open sheet</button>

      <Sheet isOpen={isOpen} onClose={() => setOpen(false)}>
        <Sheet.Container>
          <Sheet.Header />
          <Sheet.Content>{/* Your sheet content goes here */}</Sheet.Content>
          **<Sheet.Footer />**
        </Sheet.Container>
        <Sheet.Backdrop />
      </Sheet>
    </>
  );
