### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'scrollable.scrollTop')

### ISSUE THREAD

**Issue by mizdra** [Temzasse/react-modal-sheet#151]
## Problem

If react-modal-sheet is mounted while the user is touching the screen, the error `TypeError: undefined is not an object (evaluating 'scrollable.scrollTop')` will occur.

How to produce:

1. Open [this page](https://czvyx4-5173.csb.app/)
2. Tap anywhere on the screen.
3. Wait three seconds, then `<Sheet isOpen={true} />` is mounted.
4. If you swipe the screen, the error occurs.

<img width="695" alt="image" src="https://github.com/Temzasse/react-modal-sheet/assets/9639995/26a3f3a5-d661-4d95-ade5-06fad15ee1c9">

code:
- [codesandbox's link](https://codesandbox.io/p/devbox/serene-gianmarco-czvyx4?embed=1&file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clps1y2t700073b6imcn69caw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clps1y2t600023b6ihl9gvhqf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clps1y2t600043b6iau4mlfis%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clps1y2t600063b6ipdxdzl0m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clps1y2t600023b6ihl9gvhqf%2522%253A%257B%2522id%2522%253A%2522clps1y2t600023b6ihl9gvhqf%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clps1y2t600063b6ipdxdzl0m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps1y2t600053b6i9k7cu0ai%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clps1y2t600063b6ipdxdzl0m%2522%252C%2522activeTabId%2522%253A%2522clps1y2t600053b6i9k7cu0ai%2522%257D%252C%2522clps1y2t600043b6iau4mlfis%2522%253A%257B%2522id%2522%253A%2522clps1y2t600043b6iau4mlfis%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clps1y2t600033b6i71tmrmuc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clps1y2t600033b6i71tmrmuc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Environment:
- OS: iOS 16.7
- Browser: Safari 16.7

It seems that the following line is `scrollable === undefined` and an error occurs.

https://github.com/Temzasse/react-modal-sheet/blob/a25d023fdda60dfa378969c0669c635d8a1dc485/src/use-prevent-scroll.ts#L135
 

## Solution
Perhaps `scrollable` is `undefined` because onTouchMove is called without calling the onTouchStart function. When `scrollable === undefined`, the process should be terminated as follows.

```js
  let onTouchMove = (e: TouchEvent) => {
    // Prevent scrolling the window.
    if (
      scrollable === undefined || // add
      scrollable === document.documentElement ||
      scrollable === document.body
    ) {
      e.preventDefault();
      return;
    }
    // ...
}
```

**Comment by Temzasse** [comment]
Fixed in [v2.2.1](https://github.com/Temzasse/react-modal-sheet/releases/tag/v2.2.1).
