### ISSUE TITLE
prevent Closing component

### ISSUE THREAD

**Issue by danilesky** [Temzasse/react-modal-sheet#153]
Hello , i would like to ask if would be possible somehow disable closing , when i swipe out too much downside modal will dissapear and it sets z-index to -1 and visibility to hidden.

What i want to achieve : On swipe down too fast , i want my modal sheet to stay at the lowest snapPoint not to dissapear. 

Thanks for answear :)

**Comment by lucasdemoraesc** [comment]
Hi @danilesky, I just had this same problem here. Looking around here in the repo I found this workaround https://github.com/Temzasse/react-modal-sheet/issues/6#issuecomment-967702561 .

This solved my problem, but I didn't want to use snapPoints, so the `disableDrag` property was a better fit:

```jsx
<Sheet
    isOpen={props.isOpen}
    onClose={() => toast.warning("Por favor, selecione uma empresa para continuar.")}
    disableDrag
    detent="content-height"
    disableScrollLocking
>
    {...}
</Sheet>
```

**Comment by danilesky** [comment]
Hello @lucasdemoraesc , thanks for answear , i already solved it by myself with almost same solution . Anyways , thanks for your interest :)
