### ISSUE TITLE
Bug: page overflow when mobile on screen keyboard is active (chrome)

### ISSUE THREAD

**Issue by rushill2** [Temzasse/react-modal-sheet#157]
There seems to be an issue that causes body scroll when the modal is overlayed on an `infinite-scroll` component, and the on screen keyboard opens. As a result, on chrome, the entire page body scrolls for the amount of space taken up by the keyboard. On firefox however, this does not seem to be the case

**Comment by Temzasse** [comment]
Hi 👋🏻 

This library doesn't provide a built-in solution for handling the virtual keyboard on mobile, but I've added a section to the docs about [virtual keyboard avoidance](https://github.com/Temzasse/react-modal-sheet?tab=readme-ov-file#%EF%B8%8F-virtual-keyboard-avoidance).

Hopefully that helps! 😎
