### ISSUE TITLE
set id for sheet for custom styling

### ISSUE THREAD

**Issue by fairhat** [Temzasse/react-modal-sheet#16]
could you allow us to set an id for the sheet container?

Right now this assumes that only one sheet would exist on the page, however i am using multiple (and want to have them different widths on desktop) but custom styling is always applied to the classes.

Something like ``` <Sheet id="custom-sheet"></Sheet>``` should be enough

Edit: Seems like setting an id for sheet.container actually works, however typescript is unable to identify the props. Maybe you could update the PropTypes with React.ButtonHTMLAttributes<HTMLDivElement> and Framer-Motion Props?

**Comment by Temzasse** [comment]
Good catch! 🙌🏻  I will add `React.HTMLAttributes<HTMLDivElement>` to the sheet props type declaration which should fix this. This will be available in the next release which will be `v1.3.1`.
