### ISSUE TITLE
Drag functionality with Scroller

### ISSUE THREAD

**Issue by wiktorstankiewicz** [Temzasse/react-modal-sheet#160]
Is there any way to resize the sheet using drag gestures, when using Scroller?

**Comment by Temzasse** [comment]
If by resizing you mean changing the snap point of the sheet with scrollable content in it, then yes:
- Code: https://github.com/Temzasse/react-modal-sheet/blob/main/example/components/ScrollableSnapPoints.tsx
- Demo: https://temzasse.github.io/react-modal-sheet/#/scrollable-snap-points
