### ISSUE TITLE
Project Still Maintained?

### ISSUE THREAD

**Issue by salemlf** [Temzasse/react-modal-sheet#161]
Is this project still maintained? Wondering because it looks like there hasn't been any updates for 7 months.

**Comment by Temzasse** [comment]
Hi 👋🏻 

I haven't had the time and energy to maintain this library for a while but now that I finally managed to get "The Great Resurrection" PR #141 merged it is much easier for me to continue developing this library.

So yes, this project is still maintained 🤓
