### ISSUE TITLE
Everthing is working but getting some 31 warnings what are these warnings

### ISSUE THREAD

**Issue by Naiduchandrasekhar** [Temzasse/react-modal-sheet#164]
WARNING in ./node_modules/@react-aria/utils/dist/useEffectEvent.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useEffectEvent.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useEffectEvent.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useEvent.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useEvent.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useEvent.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useFormReset.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useFormReset.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useFormReset.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useGlobalListeners.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useGlobalListeners.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useGlobalListeners.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useId.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useId.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useId.mjs.map'      

WARNING in ./node_modules/@react-aria/utils/dist/useLabels.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useLabels.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useLabels.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useLayoutEffect.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useLayoutEffect.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useLayoutEffect.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useObjectRef.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useObjectRef.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useObjectRef.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useResizeObserver.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useResizeObserver.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useResizeObserver.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useSyncRef.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useSyncRef.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useSyncRef.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useUpdateEffect.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useUpdateEffect.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useUpdateEffect.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useValueEffect.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useValueEffect.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useValueEffect.mjs.map'

WARNING in ./node_modules/@react-aria/utils/dist/useViewportSize.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useViewportSize.mjs.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\cs645\OneDrive\Desktop\React Projects\vaul\node_modules\@react-aria\utils\dist\useViewportSize.mjs.map'

webpack compiled with 31 warnings

**Comment by tannerbaum** [comment]
This is a bug caused by missing source maps in one of this package's dependencies, react aria. They released a fix to that a few weeks back, and I have submitted a PR to react-modal-sheet to update it.

Until the maintainer accepts the change this shouldn't affect usage of modal-sheet at all.

**Comment by Temzasse** [comment]
I've updated the react-aria related dependency which should fix this issue.
