### ISSUE TITLE
Incompatibility with react 19

### ISSUE THREAD

**Issue by laem** [Temzasse/react-modal-sheet#166]
https://github.com/framer/motion/issues/2668#issuecomment-2161555550

**Comment by Temzasse** [comment]
Thanks for the headsup 👍🏻 

I'll add React 19 support once it has been released as a stable version and once Framer Motion supports it in a stable version as well.

**Comment by huynq-appota** [comment]
@Temzasse  Framer Motion supported React 19. Could you guys to upgrade react-modal-sheet

**Comment by incseeuuu** [comment]
Yes, @Temzasse We are really looking forward to the update

**Comment by Temzasse** [comment]
This has been fixed in [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0).

> [!NOTE]
> The version 4 has breaking changes as it expects `motion` as peer dependency so you need to migrate to the new [Motion](https://motion.dev/) package that has replaced `framer-motion`.
