### ISSUE TITLE
Property 'document' does not exist on first use only

### ISSUE THREAD

**Issue by ShivaniNTT** [Temzasse/react-modal-sheet#170]
I install library and dependency too and then written code and when I tried to open the bottom sheet it says
![image](https://github.com/user-attachments/assets/f1d1953f-f1d9-44b0-8082-7e1df4b52dd5)

My code - 
`<Sheet isOpen={isModalVisible} onClose={() => setModalVisible(false)}>
				<Sheet.Container>
					<Sheet.Header />
					<Sheet.Content>
				<LoginForm
					isModalVisible={isModalVisible}
					setModalVisible={setModalVisible}
				/>
				</Sheet.Content>
				</Sheet.Container>
				<Sheet.Backdrop />
			</Sheet>`

**Comment by carlos-ribeiro-zup** [comment]
are you trying to use it within react-native?
there is a better lib to use with react-native [@gorhom/bottom-sheet](https://www.npmjs.com/package/@gorhom/bottom-sheet)

**Comment by Temzasse** [comment]
Yeah @carlos-ribeiro-zup's comment is correct. This library is intended only for Web and not for React Native.
