### ISSUE TITLE
I can not control z-index of <Sheet>

### ISSUE THREAD

**Issue by AK1118** [Temzasse/react-modal-sheet#173]

**Comment by Temzasse** [comment]
Hey @AK1118 👋🏻 

Could you describe the use case a bit more? Do you want to control the z-index of the wrapper div of the sheet which currently just uses a hard coded z-index value of 9999999 when sheet is open and -1 when it is closed?

**Comment by AK1118** [comment]
I've been trying to rewrite the stylesheet for that other component class in index.css, and it worked. If you add a control method ,It would be even better.

index.css
```
.react-modal-sheet-container {
  /* custom styles */
  z-index: 2 !important;
}
.react-modal-sheet-backdrop {
  /* custom styles */
  z-index: 1 !important;
}
.react-modal-sheet-header {
  /* custom styles */
}
.react-modal-sheet-drag-indicator {
  /* custom styles */
}
.react-modal-sheet-content {
  /* custom styles */
}
.PhotoView-Portal{
  z-index:999999999 !important;
}
.Toastify__toast-container{
  z-index:999999999 !important;
}
```

**Comment by khashashin** [comment]
Changing the z-index using the following example worked for me: https://github.com/Temzasse/react-modal-sheet/issues/144#issuecomment-1807431040

**Comment by Temzasse** [comment]
This has been fixed in [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0). If you pass `<Sheet style={{ zIndex: 123 }}` it will be used instead of a hard coded value.

> [!NOTE]
> The version 4 has breaking changes as it expects `motion` as peer dependency so you need to migrate to the new [Motion](https://motion.dev/) package that has replaced `framer-motion`.
