### ISSUE TITLE
[Request] type export for each sub-component

### ISSUE THREAD

**Issue by Moon-Sangho** [Temzasse/react-modal-sheet#174]
In my project, there is a component that standardizes the design by wrapping the components provided by the react-modal-sheet library. 
In version 2.2.1, the types of each sub-component were exported, so I could use them like the code block below. I would appreciate it if you could export the types of the subcomponents again.
Thank you.

```typescript
...

import {
  SheetBackdropProps,
  SheetContainerProps,
  SheetProps,
} from 'react-modal-sheet/dist/types';

type BottomSheetProps = Readonly<SheetProps & {
    containerProps?: SheetContainerProps;
    backdropProps?: SheetBackdropProps;
    ...
}
```

**Comment by Temzasse** [comment]
Hey @Moon-Sangho 👋🏻 

This has been fixed in [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0).

> [!NOTE]
> The version 4 has breaking changes as it expects `motion` as peer dependency so you need to migrate to the new [Motion](https://motion.dev/) package that has replaced `framer-motion`.

You can now import the types directly from the package like so:

```ts
import {
  Sheet,
  type SheetProps,
  type SheetBackdropProps,
  type SheetHeaderProps,
  type SheetContentProps,
  type SheetScrollerProps,
  type SheetContainerProps,
} from 'react-modal-sheet';
```
