### ISSUE TITLE
Sheet.Scroller in a shadow root doesn't scroll

### ISSUE THREAD

**Issue by alexkates** [Temzasse/react-modal-sheet#176]
Please find an example in my fork here: https://github.com/alexkates/react-modal-sheet/blob/scrollable-shadow-root-bug/example/components/ScrollableInShadowRoot.tsx

When placing a Sheet with a Scroller inside of an open shadow root, the scroller does not work as expected. It simply doesn't scroll.

Steps to reproduce: 
1. Checkout my fork linked above.
2. Install and run `npm run dev` from the root.
3. cd example and run `npm run dev -- --host` to host the example app publicly.
4. Access the external IP from an iOS simulator.
5. Open the new "Scrollable in shadow root" example
6. Attempt to scroll.

https://github.com/user-attachments/assets/148aa67f-5d9d-426f-80ae-9bcb475a3a6e

**Comment by alexkates** [comment]
I've deployed this example to https://alexkates.github.io/react-modal-sheet/#/scrollable-shadow-root

**Comment by alexkates** [comment]
I've opened a pull request with a fix for this https://github.com/Temzasse/react-modal-sheet/pull/179

**Comment by Temzasse** [comment]
@alexkates Thank you for reporting this and opening the PR 🙏🏻 

I have shipped your fixes in [v3.5.0](https://github.com/Temzasse/react-modal-sheet/releases/tag/v3.5.0) release 😊
