### ISSUE TITLE
Plan to move to `motion`?

### ISSUE THREAD

**Issue by xsjcTony** [Temzasse/react-modal-sheet#177]
As `motion` is now an independent project, I believe it will soon be used widely by many projects.
The official documentation now recommends you to `npm install motion` instead of `framer-motion` except for framer sites.
`motion/react` should just be equivalent to `framer-motion` import-wise, so maybe we should tweak this lib to use `motion` instead?

**Comment by Temzasse** [comment]
I have released [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0) that has `motion` as peer dependency instead of `framer-motion`.
