### ISSUE TITLE
framer-motion version error

### ISSUE THREAD

**Issue by Wing-Li** [Temzasse/react-modal-sheet#178]
When I introduced "framer-motion": "11.12.0" into my Next.js project, the modal functionality failed, and the bottom modal could not be displayed.

After downgrading framer-motion to version 11.1.9, the project worked properly again.

**Comment by Temzasse** [comment]
Please try using [v4](https://github.com/Temzasse/react-modal-sheet/releases/tag/v4.0.0) that supports the new `motion` package that has replace `framer-motion`.

Also make sure you have `StrictMode` turned off in your [Next.js config](https://nextjs.org/docs/pages/api-reference/config/next-config-js/reactStrictMode) as that causes problems in [Motion](https://motion.dev/): https://github.com/Temzasse/react-modal-sheet?tab=readme-ov-file#-troubleshooting
