### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by fairhat** [Temzasse/react-modal-sheet#2]
Hey,

currently using this component for SSR is impossible because ```src/sheet.tsx``` uses ```ReactDOM.createPortal(... document.body)```
document is undefined inside SSR (in my case next.js)

**Comment by Temzasse** [comment]
Thank you for reporting this 🙏 

I haven't used Next.js before but I'll take a look at this issue 👍

**Comment by Temzasse** [comment]
@fairhat I believe this issue should be fixed in version `0.1.3`.
