### ISSUE TITLE
Option to block scroll on backdrop?

### ISSUE THREAD

**Issue by 10000multiplier** [Temzasse/react-modal-sheet#20]
Would be nice if there was a prop for this 🥰

**Comment by Temzasse** [comment]
I think you should be able to achieve this without any modifications to the library itself by setting [`touch-action: none;`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to the backdrop that you render.

**Comment by 10000multiplier** [comment]
I used this library and it works very well even on safari iOS which is usually a troublemaker

https://github.com/theKashey/react-remove-scroll
