### ISSUE TITLE
SSR Support for Sheet.Content

### ISSUE THREAD

**Issue by MarkusWendorf** [Temzasse/react-modal-sheet#21]
Hi there,

would it be possible to output the Sheet.Content to the html on the server-side? 
Currently it is not possible because createPortal references part of the document (not available on the server), right?.

If the user could decide how/where to mount the Sheet this would be possible right? i.e. opting out of the createPortal logic and putting it somewhere else in the regular React tree.

**Comment by Temzasse** [comment]
Fixed in https://github.com/Temzasse/react-modal-sheet/pull/33
