### ISSUE TITLE
Couldn't run with Next js

### ISSUE THREAD

**Issue by oyhan** [Temzasse/react-modal-sheet#23]
Hi @Temzasse 
I intended to use your library with Nextjs and server side rendering but it seems it can't be done.
Even I importing using `dynamic`  and `ssr : false`

Do you have any direction?

**Comment by Temzasse** [comment]
There is an open [PR](https://github.com/Temzasse/react-modal-sheet/pull/22) about improving SSR but the author hasn't responded to my latest comments (I might have to over take the PR and get it merged).

**Comment by Temzasse** [comment]
This should be fixed in https://github.com/Temzasse/react-modal-sheet/pull/33

I will publish a new npm release soon.
