### ISSUE TITLE
Feature request: add support for from top direction?

### ISSUE THREAD

**Issue by lodisy** [Temzasse/react-modal-sheet#29]
Hello, 

I want to use the modal sheet as a swippable header, which is basically a mirrored version but probably also needs to handle the point events (like the header in the Playstation App).
 
Any idea or advice on how to make it?  Thanks.

**Comment by lodisy** [comment]
![Screenshot_20210522-175650_PS App.jpg](https://i.loli.net/2021/05/22/FXRckwxWlYbBT3u.jpg) ![Screenshot_20210522-175630_PS App.jpg](https://i.loli.net/2021/05/22/VrJdLGtPpyE2Yim.jpg)

**Comment by lodisy** [comment]
Made it by adding a fromTop param and modifying the handleDrag, and also the container animation etc.

**Comment by Roshdy** [comment]
@lodisy can you please provide an example?
