### ISSUE TITLE
Typescript Implementation Issue

### ISSUE THREAD

**Issue by franziz** [Temzasse/react-modal-sheet#4]
Hi, I am really love your work for this `react-modal-sheet`. However, I face implementation issue. Would be great if you can take a look. 

I know you are busy with your job, any help will be appreciated.

Typescript implementation with `"react-modal-sheet": "^0.1.3",`

`Type '{}' is missing the following properties from type 'Pick<MotionProps, "inherit" | "transition" | "style" | "static" | "drag" | "onDrag" | "onDragEnd" | "onDragStart" | "onAnimationStart" | "transformTemplate" | "transformValues" | ... 31 more ... | "custom">': static, positionTransition, layoutTransition, _dragValueX, and 4 more.`

```
    17 |       <Sheet isOpen={true} onClose={() => {}}>
  > 18 |         <Sheet.Backdrop />
       |          ^
    19 |       </Sheet>
```

Any idea for this issue?

Thanks

**Comment by Temzasse** [comment]
Thank you for reporting this! 

What versions are you using for `framer-motion` and `typescript`?

**Comment by franziz** [comment]
```
"typescript": "~3.7.2",
"framer-motion": "^2.9.4",
```

Thanks for replying in such a fast time. Keep safe :D

**Comment by franziz** [comment]
Just to update as well. It works on `frame-motion: 1.11.0`

**Comment by Temzasse** [comment]
Thanks for the details!

I have trouble reproducing this locally 🤔

However, I think I will just drop the support for `framer-motion` v1 and release a new version that only supports `framer-motion` v2. Hopefully that will fix this issue 🤞

**Comment by Temzasse** [comment]
@franziz I just released `1.0.0` that now only supports `framer-motion` v2 🚀 

I checked that at least on Codesandbox the new types seem to work fine now. Hopefully it works for you too!

**Comment by franziz** [comment]
It works in your `1.0.0` release!

Great! Thanks.

**Comment by bulby97** [comment]
Hi, I have this issue with:
- "framer-motion": "^3.2.0",
- "react-modal-sheet": "^1.3.0",
