### ISSUE TITLE
How to get current active snap?

### ISSUE THREAD

**Issue by nickbyte** [Temzasse/react-modal-sheet#50]
I am trying to adjust the wrapping container height based on which is the active current point, onSnap, returns negative values. So hard to identify which is the active snap

**Comment by Guiw5** [comment]
you have this handler on props

`onSnap={snapIndex =>
  console.log('> Current snap point index:', snapIndex)
}`
is the index from snapPoints array 
```
snapPoints={[600, 400, 100, 0]}
initialSnap={1}
```

**Comment by Temzasse** [comment]
@nickbyte can you provide a repro of this issue in [CodeSandbox](http://react.new/)? Or did you figure it out?

Your problem might be related to you changing the container height which will probably mess with the snap point calculations within the library 🤔

**Comment by slellampati** [comment]
I have the same problem. It gives a valid snapoint index on load but after dragging, it always gives -1.

**Comment by Guiw5** [comment]
@Temzasse I found the issue:
I was using your example from 
https://github.com/Temzasse/react-modal-sheet/blob/master/example/components/SnapPoints.tsx
but if you change the snapPoints all to percentages like:
`const snapPoints = [0.9, 0.6, 0.3, 0];`

**And just appear in responsive view**
[codesandbox](https://codesandbox.io/s/react-modal-sheet-non-closable-with-snap-points-forked-9eyccs?file=/src/App.tsx&resolutionWidth=452&resolutionHeight=678)

**Comment by Guiw5** [comment]
it would be nice if we can have access to the div from the sheet ref.

**Comment by AbBiz21** [comment]
I am having the same problem, I used the following props 
 <Sheet
       snapPoints={[0.925, 0.53, 0.19]}
      initialSnap={2}
      onSnap={(snapIndex) => {
        console.log(snapIndex);
      }} .../>

but it is giving the actual snap index on load only. Otherwise, it returns -1.
is there any way I can get the current snap index?

**Comment by Temzasse** [comment]
Thanks for reporting this 🙏🏻 This should be fixed in version [1.6.1](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.6.1) 🙂
