### ISSUE TITLE
How to disable close modal-sheet

### ISSUE THREAD

**Issue by giangjcr** [Temzasse/react-modal-sheet#51]
Hello friends
how to make my **modal-sheet** always be displayed on screen as 100px drag max 500px and can't close modal-sheet when height is 100px

**Comment by guilnorth** [comment]
> Same problem here. If you do the following, you still can close the sheet if you drag fast. `isOpen={true} onClose={()=>{}}`

Try this workaround https://github.com/Temzasse/react-modal-sheet/issues/6#issuecomment-967702561

**Comment by Temzasse** [comment]
Duplicate of #6
