### ISSUE TITLE
Property 'onViewportBoxUpdate' is missing in type '{ children: Element[]; }' but required in type 'Pick '.

### ISSUE THREAD

**Issue by parikkap** [Temzasse/react-modal-sheet#52]
Getting this error from `Sheet.Container, Sheet.Header, Sheet.Content` and` Sheet.Backdrop`. To my understanding the expected type comes from `framer-motion` library. Could you have a look into it?

**Comment by DiogoCoelhoo** [comment]
That error can be resolved with this [https://exerror.com/cant-import-the-named-export-children-from-non-ecmascript-module-only-default-export-is-available/]. 
Something happened in the `framer-motion 5.x.x version `that change the way that imports work.

**Comment by kaueburiti** [comment]
Do we have plans to update the library to be able to handle the last framer-motion version?
