### ISSUE TITLE
its too slow

### ISSUE THREAD

**Issue by torref** [Temzasse/react-modal-sheet#57]
This library has many options, it is perfect, but it is very slow when there is a lot of data in it and it creates problems especially in the performance of other component.

can you fix that and update library ? 🙏

**Comment by Temzasse** [comment]
Please take a look at [memoization](https://epicreact.dev/memoization-and-react/) if you have re-rendering problems, and you can utilize a [windowing library](https://github.com/bvaughn/react-window) if you have trouble with large amounts of data (eg. large lists).

If you have more details about performance issues related to this library please open a new issue with more info and a repro case 🙂
