### ISSUE TITLE
Is there any way to close the modal when clicking on the overlay

### ISSUE THREAD

**Issue by willianferreiradev** [Temzasse/react-modal-sheet#84]
I need to add this behavior, but I searched and didn't find anything about it. Is there a way to make it work?

**Comment by willianferreiradev** [comment]
Nice. Thanks :)

**Comment by eurobob** [comment]
I don't know if this is really appropriate?

Maybe i'm not implementing correctly, but when i attempt this, it just closes instantly with no animation.

I feel like using snapPoints is unnecessary, and a simple close method should be exposed to be manually triggered
