### ISSUE TITLE
Navigate to a page where sheet is already open skips opening animation

### ISSUE THREAD

**Issue by laripereira14** [Temzasse/react-modal-sheet#86]
I tried to open the bottom sheet as soon as the user navigates to a page with the following code:

```
//on PageOne.tsx
<Link href="/book/123"> Go to next page (PageTwo)</Link>

//PageTwo.tsx
export const PageTwo: NextPage = () => {
    const [isOpen, setIsOpen] = useState(true);
    return(
        <>
            <BottomSheet isOpen={isOpen} onClose={setIsOpen} >
                Hello!
            </BottomSheet>
        </>
    )
}
```

But when PageTwo is reached, the opening animation has already happened and can't be seen. Here's a small video I recorded to illustrate:

https://user-images.githubusercontent.com/63196108/177058342-27fea27a-e1b9-4cd5-9df2-0bfcb56f7ff0.mp4

How can I make the user see this animation? I've worked with another bottom sheet lib in the past and that was possible, is there any animation config I'm missing?
Thank you!

**Comment by Temzasse** [comment]
You can initialize the state with `false` and then open the sheet in an effect like this: 

```tsx
useEffect(() => {
  setOpen(true);
}, []);
```
