### ISSUE TITLE
How could I make the sheet not disappear when I scroll down?

### ISSUE THREAD

**Issue by francmarin98** [Temzasse/react-modal-sheet#87]
What I am looking for is that when I scroll down the sheet returns to the initial position and cannot be hidden

**Comment by FnugDev** [comment]
> What I am looking for is that when I scroll down the sheet returns to the initial position and cannot be hidden

did u find a fix?

**Comment by Temzasse** [comment]
If you don't mind losing draggability for the `Sheet.Content` then you can pass `disableDrag` to it to disable all dragging gestures for the content part of the sheet. The header will still be draggable.

```tsx
<Sheet>
  <Sheet.Container>
    <Sheet.Header />
    <Sheet.Content disableDrag>
      {/* ... */}
    </Sheet.Content>
  </Sheet.Container>
</Sheet>
```

Not sure if Framer Motion is able to handle both vertical scrollability and draggability for the content without occasionally mixing those two type of gesture events. If you think about it scrolling down is basically the same gesture as dragging down.
