### ISSUE TITLE
Hiding header at Full snap.

### ISSUE THREAD

**Issue by AbBiz21** [Temzasse/react-modal-sheet#92]
I used 3 snap points i.e [0.925, 0.53, 0.19], the starting snap point is 0.19.

in the modal I used all the elements like this...

<Sheet>
     <Sheet.Container>
          <Sheet.Header />
          <Sheet.Content>
           </Sheet.Content>
      </Sheet.Container>
</Sheet>

I was trying to hide the header at full snap. How do I do that?  I tried to get the snapIndex and use it but it is not giving the right index at each snap point.

**Comment by Temzasse** [comment]
Thanks for reporting this 🙏🏻 This should be fixed in version [1.6.1](https://github.com/Temzasse/react-modal-sheet/releases/tag/v1.6.1) 🙂
